"""
Minimum XOR Path in a Grid
Difficulty: Medium

Description:
This problem asks us to find a path from the top-left cell (0, 0) to the bottom-right cell (m-1, n-1) of a grid, moving only right or down. The cost of a path is defined as the bitwise XOR sum of all values in the cells along that path. We need to return the minimum possible XOR sum among all such valid paths.

Example:
Input: grid = [[1,2],[3,4]]
Output: 6
Explanation:
There are two valid paths:
(0, 0) -> (0, 1) -> (1, 1) with XOR: 1 XOR 2 XOR 4 = 7
(0, 0) -> (1, 0) -> (1, 1) with XOR: 1 XOR 3 XOR 4 = 6
The minimum XOR value among all valid paths is 6.

Approach:
This problem can be solved using dynamic programming. We define `dp[r][c]` as a set containing all possible XOR sums of paths from the starting cell `(0, 0)` to the current cell `(r, c)`. The base case is `dp[0][0] = {grid[0][0]}`. For any other cell `(r, c)`, the possible XOR sums are generated by taking each XOR sum from the cell above `(r-1, c)` and XORing it with `grid[r][c]`, and similarly for each XOR sum from the cell to the left `(r, c-1)` and XORing it with `grid[r][c]`. Since `grid[i][j]` values are up to 1023 (which is `2^10 - 1`), any XOR sum will also be within the range `[0, 1023]`. This means each set `dp[r][c]` will contain at most `2^10 = 1024` distinct values. We iterate through the grid in row-major order, filling `dp[r][c]` for each cell based on its predecessors. Finally, the minimum XOR value is the minimum element in the set `dp[m-1][n-1]` once the entire grid has been processed.

Time Complexity: O(m * n * MAX_POSSIBLE_XOR_VALUES)
Where `MAX_POSSIBLE_XOR_VALUES` is `2^B` for `B` bits, here `2^10 = 1024` since `grid[i][j]` is up to 1023. Given `m * n <= 1000`, the total time complexity is approximately `1000 * 1024`, which is about `10^6` operations, well within typical time limits.
Space Complexity: O(m * n * MAX_POSSIBLE_XOR_VALUES)
This is for storing `m * n` sets, each potentially holding up to `MAX_POSSIBLE_XOR_VALUES` integers. With `m * n <= 1000` and `MAX_POSSIBLE_XOR_VALUES = 1024`, the total number of integers stored is roughly `10^6`. This is also acceptable for memory constraints.
"""
from typing import List, Optional

class Solution:
    def minCost(self, grid: List[List[int]]) -> int:
        m = len(grid)
        n = len(grid[0])

        # dp[r][c] will store a set of all possible XOR sums to reach cell (r, c).
        # The values in grid[i][j] are up to 1023 (which is 2^10 - 1).
        # Thus, any XOR sum will also be within the range [0, 1023].
        # The maximum number of distinct XOR values for any path segment is 2^10 = 1024.
        dp = [[set() for _ in range(n)] for _ in range(m)]

        # Base case: The XOR sum to reach the starting cell (0, 0) is just its value.
        dp[0][0].add(grid[0][0])

        # Iterate through the grid to fill the DP table
        for r in range(m):
            for c in range(n):
                # We already handled the base case (0, 0), so skip it in the loop
                if r == 0 and c == 0:
                    continue

                current_cell_value = grid[r][c]

                # Option 1: Come from the cell above (r-1, c)
                if r > 0:
                    for prev_xor_sum in dp[r-1][c]:
                        dp[r][c].add(prev_xor_sum ^ current_cell_value)
                
                # Option 2: Come from the cell to the left (r, c-1)
                if c > 0:
                    for prev_xor_sum in dp[r][c-1]:
                        dp[r][c].add(prev_xor_sum ^ current_cell_value)
        
        # The result is the minimum value in the set of XOR sums for the bottom-right cell
        return min(dp[m-1][n-1])

if __name__ == "__main__":
    s = Solution()

    # Example 1
    grid1 = [[1,2],[3,4]]
    assert s.minCost(grid1) == 6, f"Test 1 failed. Expected 6, got {s.minCost(grid1)}"

    # Example 2
    grid2 = [[6,7],[5,8]]
    assert s.minCost(grid2) == 9, f"Test 2 failed. Expected 9, got {s.minCost(grid2)}"

    # Example 3
    grid3 = [[2,7,5]]
    assert s.minCost(grid3) == 0, f"Test 3 failed. Expected 0, got {s.minCost(grid3)}"

    # Additional test cases

    # 1x1 grid
    grid4 = [[10]]
    assert s.minCost(grid4) == 10, f"Test 4 failed. Expected 10, got {s.minCost(grid4)}"

    # Path only down
    grid5 = [[1],[2],[3]]
    # Path: 1 -> 2 -> 3. XOR: 1^2^3 = 3^3 = 0
    assert s.minCost(grid5) == 0, f"Test 5 failed. Expected 0, got {s.minCost(grid5)}"

    # Path only right
    grid6 = [[10, 20, 30]]
    # Path: 10 -> 20 -> 30. XOR: 10^20^30 = 22^30 = 8
    assert s.minCost(grid6) == (10 ^ 20 ^ 30), f"Test 6 failed. Expected {10^20^30}, got {s.minCost(grid6)}"

    # Grid with zeros
    grid7 = [[0,0],[0,0]]
    assert s.minCost(grid7) == 0, f"Test 7 failed. Expected 0, got {s.minCost(grid7)}"

    # Larger grid with all 1s
    grid8 = [[1,1,1],[1,1,1],[1,1,1]]
    # For a 3x3 grid, any path has length m+n-1 = 3+3-1 = 5 cells.
    # The XOR sum of 5 ones is 1.
    assert s.minCost(grid8) == 1, f"Test 8 failed. Expected 1, got {s.minCost(grid8)}"

    # Max path length example (1xN grid)
    grid9 = [[1, 2, 3, 4]]
    # Path: 1 -> 2 -> 3 -> 4. XOR: 1^2^3^4 = 3^3^4 = 0^4 = 4
    assert s.minCost(grid9) == (1 ^ 2 ^ 3 ^ 4), f"Test 9 failed. Expected {1^2^3^4}, got {s.minCost(grid9)}"

    print("All tests passed!")